### ISSUE TITLE
Redundant CSS tags

### ISSUE THREAD

**Issue by martoio** [trevortrevdc/prj-rev-bwfs-dasmoto#4]
There's no real benefit of adding this to the CSS if you aren't actually using it to style anything.

https://github.com/trevortrevdc/prj-rev-bwfs-dasmoto/blob/606c124dc71103a61fea6953f87a662a9bf16279/dasmoto/resources/css/style.css#L13-L15

**Comment by trevortrevdc** [comment]
Added properties and values to eliminate redundancies elsewhere.
