### ISSUE TITLE
Duplicate CSS

### ISSUE THREAD

**Issue by martoio** [trevortrevdc/prj-rev-bwfs-dasmoto#5]
See how this code repeats 3 times for each ``h2``?

https://github.com/trevortrevdc/prj-rev-bwfs-dasmoto/blob/606c124dc71103a61fea6953f87a662a9bf16279/dasmoto/resources/css/style.css#L19-L21

What happens if the client decides to change the font-size and the color for the ``h2``s? All of a sudden you have to make 6 edits in your code, when in reality you are only changing 2 things. A better approach would be:
```
.product h2{
  font-size:32px;
  font-weight:bold;
  color: white;
}
#brushes {
  background-color: mediumspringgreen;
}

#frames {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

**Comment by trevortrevdc** [comment]
Good suggestion! This is what I believe I was trying to do, but didn't quite grasp it. Thanks!
